pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                //get some code from a github repository
                git 'https://github.com/dsamist/python_prac'
            }
        }
    }
}