pipeline {
    agent any

    tools {
        go '1.22.0'
    }

    environment {
        GO111MODULE = 'on'
    }

    stages {
        stage('Test') {
            steps {
                git 'https://github.com/AdminTurnedDevOps/go-webapp-sample.git'
    }
}
        stage('Build') {
            steps {
                git  'https://github.com/AdminTurnedDevOps/go-webapp-sample.git'
                sh 'go build .'
               // sh './go-webapp-sample'
            }
        }

        stage('Run'){
            steps {
                sh 'cd /var/jenkins_home/workspace/go-full-pipeline && go-web-sample &'
            }
        }
    }
}





/////////////////////////////////////////////////////////////

pipeline {
    agent {
        label {
            label 'master'
            customWorkspace "${JENKINS_HOME}/${BUILD_NUMBER}/"
        }
    }
    environment {
        Go111MODULE='on'
    }
    
    stages {
        stage ('go-test'){
            steps {
                git 'https://github.com/kodekloudhub/go-webapp-sample.git'
            }
        }
        
        stage('docker build'){
            steps {
                script {
                    app = docker.build("adminturneddevops/go-webapp-sample")
                }
                sh "docker run -p 8090:8000 -d adminturneddevops/go-webapp-sample"
            }
        }
    }
}