pipeline {
    agent any

    tools {
        go '1.22.0'
    }

    environment {
        GO111MODULE = 'on'
    }

    stages {
        stage('test'){
            steps {
                git 'https://github.com/AdminTurnedDevOps/go-webapp-sample.git'
                sh 'go test ./...'
            }
        }

    }
}